package com.quizwebsite.servlet;

import com.quizwebsite.dao.AnswerDAO;
import com.quizwebsite.dao.QuestionDAO;
import com.quizwebsite.dao.QuestionOptionDAO;
import com.quizwebsite.model.*;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import java.io.IOException;
import java.sql.SQLException;

@WebServlet("/AddQuestionServlet")
public class AddQuestionServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        User user = (User) session.getAttribute("user");
        Long quizId   = (Long)    session.getAttribute("newQuizId");
        Integer position = (Integer) session.getAttribute("questionPosition");

        String typeStr      = request.getParameter("questionType");
        String questionText = request.getParameter("questionText");
        String action       = request.getParameter("action"); //"addAnother" or "finish"//

        //does validation//
        if (questionText == null || questionText.trim().isEmpty()) {
            request.setAttribute("error", "Question text cannot be empty.");
            request.getRequestDispatcher("addQuestion.jsp").forward(request, response);
            return;
        }

        QuestionType type;
        try {
            type = QuestionType.valueOf(typeStr);
        } catch (IllegalArgumentException e) {
            request.setAttribute("error", "Invalid question type.");
            request.getRequestDispatcher("addQuestion.jsp").forward(request, response);
            return;
        }

        try {
            QuestionDAO questionDAO = new QuestionDAO();
            AnswerDAO answerDAO = new AnswerDAO();
            QuestionOptionDAO optionDAO = new QuestionOptionDAO();

            //determines imageUrl, which is only used for PICTURE_RESPONSE//
            String imageUrl = null;
            if (type == QuestionType.PICTURE_RESPONSE) {
                imageUrl = request.getParameter("imageUrl");
            }

            //builds the Question using QuestionFactory//
            Question question = QuestionFactory.create(
                    type,
                    0,                        // is generated by DB//
                    quizId,
                    questionText.trim(),
                    imageUrl,
                    position
            );

            //inserts question, gets generated ID//
            long questionId = questionDAO.insert(question);

            //now saves the answer(s) / options depending on type//
            if (type == QuestionType.QUESTION_RESPONSE || type == QuestionType.FILL_BLANK) {
                String correctAnswer = request.getParameter("correctAnswer");
                if (correctAnswer != null && !correctAnswer.trim().isEmpty()) {
                    //slot_index is null for simple single answers//
                    answerDAO.insert(new Answer(0, questionId, correctAnswer.trim(), null));
                }

            } else if (type == QuestionType.MULTIPLE_CHOICE) {
                String correctIndexStr = request.getParameter("correctOption");
                int correctIndex = (correctIndexStr != null) ? Integer.parseInt(correctIndexStr) : 0;

                for (int i = 0; i < 4; i++) {
                    String optText = request.getParameter("option" + i);
                    if (optText != null && !optText.trim().isEmpty()) {
                        optionDAO.insert(new QuestionOption(
                                0,          // id is generated by DB//
                                questionId,
                                optText.trim(),
                                i == correctIndex
                        ));
                    }
                }

            } else if (type == QuestionType.PICTURE_RESPONSE) {
                String correctAnswer = request.getParameter("correctAnswerPicture");
                if (correctAnswer != null && !correctAnswer.trim().isEmpty()) {
                    answerDAO.insert(new Answer(0, questionId, correctAnswer.trim(), null));
                }
            }

            //increments position in session//
            session.setAttribute("questionPosition", position + 1);

            if ("finish".equals(action)) {
                //cleans up session variables used during creation//
                long savedQuizId = quizId;
                session.removeAttribute("newQuizId");
                session.removeAttribute("newQuizTitle");
                session.removeAttribute("questionPosition");

                response.sendRedirect("quizCreated.jsp?quizId=" + savedQuizId);
            } else {
                //adds another question//
                response.sendRedirect("addQuestion.jsp");
            }

        } catch (SQLException e) {
            throw new ServletException("DB error saving question", e);
        }
    }
}